name: Continuous Integration

on:
    push:
        branches:
            - main

env:
    NODE_VERSION: 18

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v4

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Format files
              run: pnpm format

    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v4

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Typecheck files
              run: pnpm typecheck

    tests:
        name: Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v4

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Test files
              run: pnpm test
