name: Release

on:
    workflow_dispatch:

env:
    FRONTIFY_INSTANCE_DOMAIN: "frontify.alev.cloud"

jobs:
    linting:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Lint files
              run: pnpm lint

    typecheck:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Typecheck files
              run: pnpm typecheck

    tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Test files
              run: pnpm test

    deployment:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: [linting, typecheck, tests]

        steps:
            - name: Checkout current commit
              uses: actions/checkout@v3

            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Deploy apps
              uses: SamuelAlev/frontify-app-deploy@v1
              env:
                  NODE_OPTIONS: "--max_old_space_size=7168"
              with:
                  path: "./apps/*"
                  instanceDomain: ${{ env.FRONTIFY_INSTANCE_DOMAIN }}
                  token: ${{ secrets.FRONTIFY_TOKEN }}
